image: node:latest

before_script:
  - npm install retypeapp --global

stages:
  - deploy

pages:
  stage: deploy
  script:
  - retype build --password 8k64MtD5ry6t --pro --output public
  artifacts:
    paths:
    - public/
  only:
  - main
